Deploy directly without PR

diff --git a/.github/workflows/publish-package.yml b/.github/workflows/publish-package.yml
--- a/.github/workflows/publish-package.yml
+++ b/.github/workflows/publish-package.yml
@@ -22,12 +22,29 @@ jobs:
       - name: Build All Packages in Dependency Order
         run: yarn build
 
+      # This step will run changeset version, setting the step output to if there were changesets found
+      - name: Version command
+        id: version
+        run: |
+          echo ::set-output name=changes::$(yarn version-packages 2>&1 | grep -q 'No unreleased changesets found' && echo 'false' || echo 'true')
+
+      # Push the updated package.json, and CHANGESET.md files to github, this will trigger a new build
+      # the || echo 'No changes' is to ignore errors from git when trying to commit and there are no changes
+      - name: Push changes
+        if: steps.version.outputs.changes == 'true'
+        run: |
+          git config user.email "<email>"
+          git config user.name "<name>"
+          git add -A
+          git commit -m "Version packages" || echo "No changes to commit"
+          git push
+
       - name: Create Release Pull Request or Publish to npm
         id: changesets
         uses: changesets/action@v1
         with:
-          version: yarn version-packages
           publish: yarn release
+          createGithubReleases: false
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
